[package]
name = "leiden-optimisation"
version = "0.1.0"
edition = "2021"
authors = ["Planters"]

[dependencies]
approx = "0.5.1"
clap = { version = "4.4.11", features = ["derive"] }
compute = "0.2.3"
csv = "1.3.0"
getset = "0.1.2"
plotters = "0.3.5"
serde = "1.0.197"
serde_json = "1.0.114"