[package]
name = "leiden-optimisation"
version = "0.1.0"
edition = "2021"
authors = ["Planters"]

[dependencies]
approx = "0.5.1"
clap = { version = "4.4.11", features = ["derive"] }
csv = "1.3.0"
getset = "0.1.2"